spring.datasource.url=jdbc:postgresql://localhost:5432/gamestrans
spring.datasource.username=gamestrans_user
spring.datasource.password=devpassword
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.web.error.include-stacktrace=always