spring.application.name=gamestrans
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=32MB

spring.thymeleaf.cache=false

